# These are supported funding model platforms

github: vijay922
patreon: vijay
open_collective: vijay9922
ko_fi: vijay9922
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: vijay9922
issuehunt: vijay9922
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: vijay9922
buy_me_a_coffee: https://buymeacoffee.com/vijay922
thanks_dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
